name: Testing

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  linux_tests:
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: true
      matrix:
        php: [ 8.1, 8.0, 7.4, 7.3, 7.2 ]
        stability: [ prefer-stable, prefer-lowest ]
        exclude:
          - php: 8.1
            stability: prefer-lowest

    name: PHP ${{ matrix.php }} - ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

      - name: Execute phpcs
        run: php vendor/bin/phpcs

      - name: Execute tests
        run: phpdbg -qrr vendor/bin/phpunit

      - name: Code coverage
        uses: codecov/codecov-action@v1
